import { NavBar } from "@/components/NavBar";
import { Footer } from "@/components/Footer";
import PageLoadDateTime from "@/components/PageLoadDateTime";
import { Suspense } from "react";
import { readLinksFromCSV } from "@/lib/csvUtils";
import { LinksList } from "@/components/LinksList";

export const dynamic = 'force-dynamic';

// @ts-expect-error Server Component
export default async function BlogPage({ searchParams }) {
  const currentPage = searchParams?.page ? parseInt(String(searchParams.page), 10) : 1;
  const itemsPerPage = 20; // Количество ссылок на странице

  // Получаем данные из CSV файла
  const { links, totalPages } = await readLinksFromCSV(currentPage, itemsPerPage);

  return (
    <>
      <NavBar />
      <main className="py-8 px-4">
        <div className="container mx-auto max-w-6xl">
          <h1 className="text-2xl mb-6">
            Статистика обратных ссылок от{" "}
            <Suspense fallback={<span>загрузка...</span>}>
              <PageLoadDateTime />
            </Suspense>
          </h1>

          <LinksList 
            links={links} 
            currentPage={currentPage} 
            totalPages={totalPages} 
          />

          <div className="mt-8 pt-4 border-t text-xs text-gray-500">
            Generated by Webmaster Yandex 2.1. Показано запросов за день: <PageLoadDateTime />
            <br />
            Страница {currentPage} из {totalPages.toLocaleString()}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
} 